### ISSUE TITLE
Create Flutter UI

### ISSUE THREAD

**Issue by rio-codes** [rio-codes/fitchii#1]
Create Flutter UI in Flutterflow

**Comment by Pranav371** [comment]
Hello 
Can u explain more precisely what is the project to be done.
I am a flutter beginner and I think I can contribute to the project

**Comment by rio-codes** [comment]
Hi @Pranav371 , this is a personal project and is still in the planning stages. I have decided not to use Flutterflow because it requires the use of Firestore, my plan is to use an AWS S3 bucket instead for storing images because there will be a huge amount of images if this scales up. I may need your help in the future but for now I am going to close this since it is no longer relevant. Thank you for the offer!

**Comment by masa2el** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
luccasr73, @mcne65, @rpseth, @jc92, @the-real-astro, @ncitron, @tiagofneto, @suolike, @Klex666, @wakakajp, @philipslcd, @Wzy-source, @xzxxzzzz000, @massun-onibakuchi, @Pai-Sho, @deviou5, @masonmahaffey, @ravsau, @proghax333, @Squid468, @gardenias, @usamagas20, @QuintusTheFifth, @nodeicode, @wayne5540, @darkwarshadow, @kennethkoch, @DeFiesta, @jooit, @izzetemredemir, @taniacua, @sectore, @mtorry225, @ystory, @dendisuhubdy, @stefan-toubia, @sohkai, @bogos, @nhuxhr, @prettyu2021, @bipinu, @ranakun, @interzone2001, @Szkered, @jajukajulz, @bingryan, @awproduct, @edurbrito, @yunsankai, @tayamino
